scene = stlread("C:\Users\alber\Desktop\TestTask.stl");
d = readtable("C:\Users\alber\Desktop\SandBox_2\SandBox_2_VFs.csv");
t = readtable("C:\Users\alber\Desktop\SandBox_2\SandBox_2_traj0.csv");
t2 = readtable("C:\Users\alber\Desktop\SandBox_2\SandBox_2_traj1.csv");
o = readtable("C:\Users\alber\Desktop\SandBox_2\SandBox_2_obst0.csv");
o2 = readtable("C:\Users\alber\Desktop\SandBox_2\SandBox_2_obst1.csv");
close
figure
trisurf(scene,'FaceColor','#AAAAAA')
hold on
xlabel('X');ylabel('Y');zlabel('Z');
plot3(-d.PositionX,-d.PositionZ,d.PositionY,'-r','LineWidth',2)
plot3(-t.X,-t.Z,t.Y,'-g','LineWidth',2)
plot3(-t2.X,-t2.Z,t2.Y,'-m','LineWidth',2)
scatter3(-o.X,-o.Z,o.Y,'r','filled')
scatter3(-o2.X,-o2.Z,o2.Y,'r','filled')
s=10;
quiver3(-d.PositionX,-d.PositionZ, d.PositionY,...
    -d.TrajectoryGuidanceVF_X0,...
    -d.TrajectoryGuidanceVF_Z0,...
    d.TrajectoryGuidanceVF_Y0,s,'b','filled');
quiver3(-d.PositionX,-d.PositionZ, d.PositionY,...
    -d.TrajectoryGuidanceVF_X1,...
    -d.TrajectoryGuidanceVF_Z1,...
    d.TrajectoryGuidanceVF_Y1,s,'c','filled');
quiver3(-d.PositionX,-d.PositionZ, d.PositionY,...
    -d.ObstacleAvoidanceForceFieldVF_X0,...
    -d.ObstacleAvoidanceForceFieldVF_Z0,...
    d.ObstacleAvoidanceForceFieldVF_Y0,s,'y','filled');
quiver3(-d.PositionX,-d.PositionZ, d.PositionY,...
    -d.ObstacleAvoidanceForceFieldVF_X1,...
    -d.ObstacleAvoidanceForceFieldVF_Z1,...
    d.ObstacleAvoidanceForceFieldVF_Y1,s,'g','filled');
axis equal
legend("Scene","Trajectory","Force","Location","northeast")