(cl:defpackage file_server-srv
  (:use )
  (:export
   "GETBINARYFILE"
   "<GETBINARYFILE-REQUEST>"
   "GETBINARYFILE-REQUEST"
   "<GETBINARYFILE-RESPONSE>"
   "GETBINARYFILE-RESPONSE"
   "SAVEBINARYFILE"
   "<SAVEBINARYFILE-REQUEST>"
   "SAVEBINARYFILE-REQUEST"
   "<SAVEBINARYFILE-RESPONSE>"
   "SAVEBINARYFILE-RESPONSE"
  ))

