// Generated by gencpp from file file_server/SaveBinaryFile.msg
// DO NOT EDIT!


#ifndef FILE_SERVER_MESSAGE_SAVEBINARYFILE_H
#define FILE_SERVER_MESSAGE_SAVEBINARYFILE_H

#include <ros/service_traits.h>


#include <file_server/SaveBinaryFileRequest.h>
#include <file_server/SaveBinaryFileResponse.h>


namespace file_server
{

struct SaveBinaryFile
{

typedef SaveBinaryFileRequest Request;
typedef SaveBinaryFileResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveBinaryFile
} // namespace file_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::file_server::SaveBinaryFile > {
  static const char* value()
  {
    return "3121441b66090c806f9864e12420345a";
  }

  static const char* value(const ::file_server::SaveBinaryFile&) { return value(); }
};

template<>
struct DataType< ::file_server::SaveBinaryFile > {
  static const char* value()
  {
    return "file_server/SaveBinaryFile";
  }

  static const char* value(const ::file_server::SaveBinaryFile&) { return value(); }
};


// service_traits::MD5Sum< ::file_server::SaveBinaryFileRequest> should match
// service_traits::MD5Sum< ::file_server::SaveBinaryFile >
template<>
struct MD5Sum< ::file_server::SaveBinaryFileRequest>
{
  static const char* value()
  {
    return MD5Sum< ::file_server::SaveBinaryFile >::value();
  }
  static const char* value(const ::file_server::SaveBinaryFileRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::file_server::SaveBinaryFileRequest> should match
// service_traits::DataType< ::file_server::SaveBinaryFile >
template<>
struct DataType< ::file_server::SaveBinaryFileRequest>
{
  static const char* value()
  {
    return DataType< ::file_server::SaveBinaryFile >::value();
  }
  static const char* value(const ::file_server::SaveBinaryFileRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::file_server::SaveBinaryFileResponse> should match
// service_traits::MD5Sum< ::file_server::SaveBinaryFile >
template<>
struct MD5Sum< ::file_server::SaveBinaryFileResponse>
{
  static const char* value()
  {
    return MD5Sum< ::file_server::SaveBinaryFile >::value();
  }
  static const char* value(const ::file_server::SaveBinaryFileResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::file_server::SaveBinaryFileResponse> should match
// service_traits::DataType< ::file_server::SaveBinaryFile >
template<>
struct DataType< ::file_server::SaveBinaryFileResponse>
{
  static const char* value()
  {
    return DataType< ::file_server::SaveBinaryFile >::value();
  }
  static const char* value(const ::file_server::SaveBinaryFileResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FILE_SERVER_MESSAGE_SAVEBINARYFILE_H
